Задание 1

In [1]:
import numpy as np

In [2]:
b = np.array([[1, 6], 
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [3]:
mean_a = b.mean(axis = 0)

In [4]:
mean_a

array([2. , 8.4])

Задание 2

In [5]:
a_centerd = b - mean_a

In [6]:
a_centerd

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [13]:
a_centered_sp = np.dot(a_centerd[:,0], a_centerd[:,1])

In [14]:
a_centered_sp

8.0

In [8]:
a_centered_sp / a_centerd.shape[0]

1.6

In [9]:
c = np.cov(b.transpose())

In [12]:
c

array([[1. , 2. ],
       [2. , 4.3]])